# dataset config : Sequential Recommendation
# yoochoose dataset

data_path: /content/converted_datasets/
dataset: yoochoose

USER_ID_FIELD: "session_id"
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [session_id, item_id, count, timestamp]
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50

# model config
embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: 'CE'

# Training and evaluation config
epochs: 10
train_batch_size: 4096
eval_batch_size: 4096
train_neg_sample_args: ~
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
metrics: ['Recall', 'MRR']
topk: 20
seq_len: 5
valid_metric: MRR@20
metric_decimal_place: 4